export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_ERROR = "GET_INGREDIENTS_ERROR";
export const INGREDIENTS_CONSTRUCTOR = "INGREDIENTS_CONSTRUCTOR";
export const INGREDIENT_DESC_ADD = "INGREDIENT_DESC_ADD";
export const INGREDIENT_DESC_DEL = "INGREDIENT_DESC_DEL";
export const GET_ORDER_NUMBER = "GET_ORDER_NUMBER";
export const UPD_ORDER_NUMBER = "UPD_ORDER_NUMBER";
